# Generated by Django 4.1 on 2022-08-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientcomp_name', models.CharField(max_length=80)),
                ('Work_status', models.CharField(max_length=20)),
                ('comp_logo', models.ImageField(null=True, upload_to='client')),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_comp_name', models.CharField(max_length=80)),
                ('pro_comp_logo', models.ImageField(null=True, upload_to='productcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_company', models.CharField(max_length=60)),
                ('product_price', models.CharField(max_length=20)),
                ('product_details', models.TextField()),
                ('product_img', models.ImageField(null=True, upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=60)),
                ('service_content', models.TextField()),
                ('service_img', models.ImageField(null=True, upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_category', models.CharField(max_length=60)),
                ('w_status', models.CharField(max_length=20)),
                ('w_details', models.TextField()),
                ('w_img', models.ImageField(null=True, upload_to='works')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
                ('image_url', models.ImageField(null=True, upload_to='gallery')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSQ.category')),
            ],
        ),
    ]
