# Generated by Django 4.1 on 2022-08-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSQ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodt_unit', models.CharField(max_length=20)),
                ('product_amount', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('products_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSQ.products')),
            ],
        ),
    ]
